//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToSqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class libavtorname
    {
        public long AvtorId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string NoDonate { get; set; }
        public int uid { get; set; }
        public string WebPay { get; set; }
        public string Email { get; set; }
        public string Homepage { get; set; }
        public bool Source { get; set; }
        public bool State { get; set; }
        public long SourceId { get; set; }
    }
}
