//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToSqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class libbook
    {
        public long BookId { get; set; }
        public long FileSize { get; set; }
        public System.DateTime Time { get; set; }
        public string Title { get; set; }
        public string Title1 { get; set; }
        public string Lang { get; set; }
        public string FileType { get; set; }
        public short Year { get; set; }
        public string Deleted { get; set; }
        public string Ver { get; set; }
        public string FileAuthor { get; set; }
        public long N { get; set; }
        public string keywords { get; set; }
        public byte[] md5 { get; set; }
        public string Broken { get; set; }
        public System.DateTime Modified { get; set; }
        public bool Source { get; set; }
        public bool State { get; set; }
        public long SourceId { get; set; }
    }
}
