//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToSqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class libgenrelist
    {
        public long GenreId { get; set; }
        public string GenreCode { get; set; }
        public string GenreDesc { get; set; }
        public string GenreMeta { get; set; }
    }
}
