//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToSqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class libseq
    {
        public int BookId { get; set; }
        public int SeqId { get; set; }
        public int SeqNumb { get; set; }
        public sbyte Level { get; set; }
    }
}
