//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToSqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryEntities : DbContext
    {
        public libraryEntities()
            : base("name=libraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<libavtor> libavtors { get; set; }
        public DbSet<libavtoraliase> libavtoraliases { get; set; }
        public DbSet<libavtorname> libavtornames { get; set; }
        public DbSet<libbook> libbooks { get; set; }
        public DbSet<libfilename> libfilenames { get; set; }
        public DbSet<libgenre> libgenres { get; set; }
        public DbSet<libgenrelist> libgenrelists { get; set; }
        public DbSet<libjoinedbook> libjoinedbooks { get; set; }
        public DbSet<librate> librates { get; set; }
        public DbSet<libseq> libseqs { get; set; }
        public DbSet<libseqname> libseqnames { get; set; }
        public DbSet<libtranslator> libtranslators { get; set; }
    }
}
